# Generated by Django 5.0.7 on 2024-07-23 16:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='registration_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('I', 'Individual'), ('C', 'Company')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[authentication.models.validate_gst_number]),
        ),
    ]
